### ISSUE TITLE
pattern matching?

### ISSUE THREAD

**Issue by arizvisa** [patois/HexraysToolbox#1]
if ur gonna use python, please give us pattern matching with sympy or something. hexrays schema is miserable to interact with in python. thx.

**Comment by patois** [comment]
I am well aware of the difficulties of having to use the Hexrays SDK in this context. An abstraction layer is definitely required in order to make HexraysToolbox more usable for anyone unfamiliar with the Hexrays SDK. You could still consider this a chance to learn the SDK and use it in the intended way or alternatively, add an abstraction layer of your choice on top and send a pull request my way. In its current state, please consider the project to be an idea, a proof-of-concept code that was mainly developed for personal use but shared with the public, free of charge ;-)

**Comment by arizvisa** [comment]
hah. srsly.

although, i don't think believe the issue is within the context that you expose to users with the hexraystoolbox project, but i believe it's in \_all\_ of the different python-based abstractions in general. there aren't many (if any?) hexrays-oriented plugins that have worked their way to a point where the next major improvement is an abstraction around searching the hexrays ctree which is why i dropped this complaint about the interface in an issue within your project.

i \_am\_ genuinely interested in solving this problem, though. even though i suggested sympy, i only fiddled around with it for a short while when i was first interested in hexrays abstraction, and my rudimentary playing with it resulted in performance issues when searching through reasonably-sized trees, and then in the end converting it into a "querying-type" language while abiding by the contraints of my own plugin was still too clumsy to be worth integrating. then sometime later when exporting trees into mathematica (although it provided a lot of flexibility for being somewhat of a toy language) resulted in serious memory issues as well (and of course unusable by normal users).

maybe if pep-0624 and related (https://www.python.org/dev/peps/pep-0634/) becomes a thing, then perhaps using python against the hexrays tree could end up being more effective than how we all are having to interact with it.

**Comment by patois** [comment]
I agree entirely, a project like this needs to be written with performance etc in mind which Python definitely is not the right language for. My hopes are high there will be something based on native code and which uses a proper query language in the future - I'd love to see an official implementation by HexRays. I think it'd have lots of potential not only in assisting manual reverse engineering and automating certain tasks.. Appreciate your interest in this project!
