### ISSUE TITLE
Question about the query expression

### ISSUE THREAD

**Issue by chunibalon** [patois/HexraysToolbox#2]
I have used this toolbox for some days and it is very helpful for me to locate some code patterns. However, I do not know how to write a query like the follow decompile code pattern:

1 v1=a1+0x10;
2 if(v1)
3      do something

I want to locate the code like line 1 which the left value has been passed to the if expr or others. Because the line 1 is not the sub-expr of line 2, so I think find_child_expr() function cannot work.

**Comment by patois** [comment]
I've been aware of this shortcoming of Hexrays Toolbox and it would definitely be useful if variables could be queried but haven't come up with a good solution, yet. As a workaround, for the time being, you could create two separate queries and test whether both of them match within the same function. Of course, this will potentially yield false positives but hopefully not too many so they could manually be filtered.

Your code could look like this:

```
for ea in Functions():
    if len(find_expr(ea, query_a)) and len(find_query(ea, query_b)):
        print("match in 0x%x" % ea)
```

**Comment by chunibalon** [comment]
OK, I got it! Thanks for your suggestion.

**Comment by patois** [comment]
I've finally had some time to look into it. One way to achieve what you are looking for is by implementing two separate **functions**, instead of lambda expressions and passing them to two distinct calls to find_item(). One of the functions should return true once pattern (1) is detected and also save the index of the variable that you would like to track (item.v.idx), e.g. into a global variable. The other function that matches pattern (2) is supposed to check whether the previously saved item.var.idx matches the one used in the if expression.

something like this may work:
```
TRACKED_VARS = []

def pattern_one_matcher(f, i):
   global TRACKED_VARS
   if i.op is idaapi.cot_asg:
       # this, that
       TRACKED_VARS.append(item_of_interest.v.idx)
       return True

r = hxtb.find_item(idaapi.get_screen_ea(), pattern_one_matcher)

# implement pattern_two_matcher and pass it to find_item()
```

Please let me know if that works for you
