### ISSUE TITLE
copy loop

### ISSUE THREAD

**Issue by labba** [patois/HexraysToolbox#6]
the example you gave in the copy loop doesn't find this type of code as a valid copy loop:

```
 while ( v5 )
  {
    result = func(arg, pBuffer, v4, v8);
    if ( result )
      break;
    v5 -= v8;
    v4 += v8;
    pBuffer = &chunk[v8];
    v8 = v5;
    if ( v5 > 0x1000 )
      v8 = 4096;
  }
```

this is the real life code: 

```
while(leftovers > 0)
{
    result = func(arg, chunk, offset, size_to);
    if ( result )
      break;

    offset  += size_to;
    leftovers    -= size_to;
    chunk = (void *)((uint32_t)pBuffer + size_to);

    size_to  = min(leftovers, (uint32_t)SIZE_4K);
}
```

how can i fix the example you gave to support this ?

thanks!

**Comment by labba** [comment]
thats not nice to close this issue and mark it as invalid without even saying anything .. at least you could have mark it as "question" ..

**Comment by patois** [comment]
I agree, having closed this issue with no further comment was rude.
The example code is not meant to find memory-copying loops universally but instead very heuristically and as such, if we wanted to be precise, there'd be even more things to fix, such as avoiding false positives etc.

Looking at the example code you provided, from what I can tell, there is no obvious copy operation. I presume the copy operation is in the "func" function. Based on that assumption, the question should probably have been:
* based on the "copy loops" example given, how can a hxtb query be implemented that detects a loop that calls a function that copies memory?

I encourage looking at some of the example queries that come with hxtb-shell. In particular at https://github.com/patois/HexraysToolbox/blob/master/hxtbshell_queries/realloc_find_leak.tbq which is an example for writing a query function that allows state to be saved etc. One more or less generic possible solution for detecting the code pattern above could be combining two queries (one that identifies loops and another one that identifies memory-copying functions). A less generic solution could be implementing a query that finds loops that enclose calls to functions known to copy memory. The "testing" branch of [HRDevHelper](https://github.com/patois/HRDevHelper/tree/testing) plugin may be of help - its context viewer ('V' hotkey) produces hxtb queries (lambda expressions) that can be copy-pasted into hxtb-shell. For even more complex things, I would suggest implementing custom scripts that use the Hexrays SDK directly (ctree_visitor_t) since Hexrays Toolbox is nothing but a convenience wrapper/tool/testing framework that brings its own limitations.

**Comment by labba** [comment]
thank! will look more into to it.
